stages:
  - build

build:
  stage: build
  image: registry.gitlab.com/ignys/rabbit/dockerfiles/ionic
  variables:
    STOREPASS: configure_me_at_ci_store
  script:
    - npm install
    - mkdir www
    - npm run prebuild
    - ionic cordova build --prod --release android
    - jarsigner -verbose -keystore vend.keystore platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk vend -storepass $STOREPASS
    - zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk vend.apk
  artifacts:
    paths:
      - vend.apk
